### ISSUE TITLE
I can not download program by undefined 'toString'

### ISSUE THREAD

**Issue by tmdoi** [bsiever/microbit-pxt-rotate#2]
Hello!

I am Tomoharu Doi on Osaka Metropolitan University College of Technology.

I can not comple your rotate expanded block program as follows:
https://makecode.microbit.org/_Y37ERDiR70M4

I hope some information about this problem.

**Comment by bsiever** [comment]
Hi @tmdoi 

Here's an example program that should work for both micro:bit v1 and v2: https://makecode.microbit.org/_RRxVi0RP5fsR. You can use it for any work you're doing now.  Just edit it and add your work. 

The approach for micro:bit v2 support used in that example is an awkward hack.   Martin at the Micro:bit Education Foundation provided a fix that makes my awkward hack unnecessary (described here: https://github.com/lancaster-university/codal-microbit-v2/pull/227).  Martin's fix is in recent versions of the Micro:bit v2 runtime (CODAL after 0.2.40), which is not currently used in MakeCode.   As soon as MakeCode is updated to use a more recent version of CODAL, the version of the extension that is included from the "Extension" feature of MakeCode should work.  (And v2 support works better!)

I'm closing this issue because it isn't actually an error in my work.  It's happening because the extension was added before Microsoft updated to a newer version of CODAL.  Neither of these are under my control and they are not actually flaws with the extension itself.  They are problems with timing of updates to MakeCode.

**Comment by tmdoi** [comment]
Thank you for your comment and detail information.
I can  rotate my mico:bit!

Tomoharu Doi

**Comment by bsiever** [comment]
@tmdoi Great!  I'm glad it works!
